### ISSUE TITLE
NullPointerException during RDF generation for WP3607(?)

### ISSUE THREAD

**Issue by egonw** [wikipathways/GPML2RDF#24]
```
  pathway: WP3607   84318
[  1349.034] Info:  Recognized format [Namespace: prefix "" is mapped to URI "http://pathvisio.org/GPML/2013a"]
[  1349.039] Info:  Document is valid according to the xml schema definition 'GPML2013a.xsd'
Exception in thread "main" java.lang.NullPointerException
    at com.hp.hpl.jena.datatypes.TypeMapper.getTypeByValue(TypeMapper.java:158)
    at com.hp.hpl.jena.graph.impl.LiteralLabelImpl.<init>(LiteralLabelImpl.java:136)
    at com.hp.hpl.jena.graph.impl.LiteralLabelFactory.createTypedLiteral(LiteralLabelFactory.java:99)
    at com.hp.hpl.jena.rdf.model.impl.ModelCom.createTypedLiteral(ModelCom.java:767)
    at com.hp.hpl.jena.rdf.model.impl.ResourceImpl.addLiteral(ResourceImpl.java:263)
    at org.wikipathways.wp2rdf.converter.LabelConverter.parseLabelGpml(LabelConverter.java:55)
    at org.wikipathways.wp2rdf.GpmlConverter.convertGpml(GpmlConverter.java:178)
    at org.wikipathways.wp2rdf.WPREST2RDF.main(WPREST2RDF.java:95)
Build step 'Execute shell' marked build as failure
```

**Comment by egonw** [comment]
Not possible to figure out what was wrong with this pathway; it's deleted now.
